# Generated by Django 3.1.2 on 2021-08-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_buildproject_topuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rank', models.IntegerField()),
                ('activity', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='TopUser',
        ),
    ]
