# Generated by Django 3.1.2 on 2021-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_event_staroftheweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='staroftheweek',
            name='name',
            field=models.CharField(default='aditya', max_length=200),
            preserve_default=False,
        ),
    ]
