# Generated by Django 3.1.2 on 2021-08-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_staroftheweek_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitywinner',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
