# Generated by Django 3.1.2 on 2021-08-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20210821_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitywinner',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staroftheweek',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
